name: EmtwentyCo Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  stage-1:
    name: Stage 1
    runs-on: ubuntu-latest
    steps:
      - name: Echo EmtwentyCo
        run: echo "EmtwentyCo"
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            # You can write your Azure CLI inline scripts here.

  stage-2:
    name: Stage 2
    runs-on: ubuntu-latest
    needs: stage-1
    steps:
      - name: Echo EmtwentyCo
        run: echo "EmtwentyCo"

  stage-3:
    name: Stage 3
    runs-on: ubuntu-latest
    needs: stage-1
    steps:
      - name: Echo EmtwentyCo
        run: echo "EmtwentyCo"

  stage-4:
    name: Stage 4
    runs-on: ubuntu-latest
    needs: stage-3
    environment: production
    steps:
      - name: Echo EmtwentyCo
        run: echo "EmtwentyCo"
